package modelo;
// Generated 2/10/2018 03:11:32 PM by Hibernate Tools 4.3.1

import java.util.ArrayList;
import java.util.List;
import java.io.Serializable;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Column;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;

/**
 * Alumno generated by hbm2java
 */

@Entity
@Table(name = "Alumno")
public class Alumno  implements Serializable {


    @Id
    @Column(name = "idAlumno")
     private int idAlumno;
    @Column(name = "aIdUsuario")
    @ManyToOne(fetch = FetchType.LAZY)
     private Usuario aIdUsuario;
    @OneToMany(mappedBy = "aIdAlumno")
     private List<Asesorar> asesorar = new ArrayList<>();

    public Alumno() {
    }

	
    public Alumno(int idAlumno, Usuario aIdUsuario) {
        this.idAlumno = idAlumno;
        this.aIdUsuario = aIdUsuario;
    }
    public Alumno(int idAlumno, Usuario aIdUsuario, List<Asesorar> asesorar) {
       this.idAlumno = idAlumno;
       this.aIdUsuario = aIdUsuario;
       this.asesorar = asesorar;
    }
   
    public int getIdAlumno() {
        return this.idAlumno;
    }
    
    public void setIdAlumno(int idAlumno) {
        this.idAlumno = idAlumno;
    }
    public Usuario getUsuario() {
        return this.aIdUsuario;
    }
    
    public void setUsuario(Usuario aIdUsuario) {
        this.aIdUsuario = aIdUsuario;
    }
    public List<Asesorar> getAsesorar() {
        return this.asesorar;
    }
    
    public void setAsesorar(List<Asesorar> asesorar) {
        this.asesorar = asesorar;
    }




}


