package modelo;
// Generated 2/10/2018 03:11:32 PM by Hibernate Tools 4.3.1



/**
 * Denuncia generated by hbm2java
 */
import java.io.Serializable;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Column;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.ManyToOne;

@Entity
@Table(name = "Denuncia")
public class Denuncia  implements Serializable {

    @Id
    @Column(name = "idDenuncia")
     private int idDenuncia;
    @Column(name = "dIdUsuario")
    @ManyToOne(fetch = FetchType.LAZY)
     private Usuario dIdUsuario;
    @Column(name = "motivo")     
     private String motivo;

    public Denuncia() {
    }

    public Denuncia(int idDenuncia, Usuario dIdUsuario, String motivo) {
       this.idDenuncia = idDenuncia;
       this.dIdUsuario = dIdUsuario;
       this.motivo = motivo;
    }
   
    public int getIdDenuncia() {
        return this.idDenuncia;
    }
    
    public void setIdDenuncia(int idDenuncia) {
        this.idDenuncia = idDenuncia;
    }
    public Usuario getUsuario() {
        return this.dIdUsuario;
    }
    
    public void setUsuario(Usuario dIdUsuario) {
        this.dIdUsuario = dIdUsuario;
    }
    public String getMotivo() {
        return this.motivo;
    }
    
    public void setMotivo(String motivo) {
        this.motivo = motivo;
    }




}


