package modelo;
// Generated 2/10/2018 03:11:32 PM by Hibernate Tools 4.3.1

import javax.persistence.OneToMany;
import java.util.ArrayList;
import java.util.List;
import java.util.Date;
import java.io.Serializable;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Column;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.ManyToOne;

/**
 * Horario generated by hbm2java
 */
@Entity
@Table(name = "Horario")
public class Horario  implements Serializable {

    @Id
    @Column(name = "idHorario")
     private int idHorario;
    @Column(name = "hIdProfesor")     
    @ManyToOne(fetch = FetchType.LAZY)
     private Profesor hIdprofesor;
    @Column(name = "dia")     
     private String dia;
    @Column(name = "horaInicio")     
     private Date horaInicio;
    @Column(name = "horaFin")     
     private Date horaFin;
    @Column(name = "disponible")     
     private Boolean disponible;
    @OneToMany(mappedBy = "aIdHorario")
     private List<Asesorar> asesorar = new ArrayList<>();

    public Horario() {
    }

	
    public Horario(int idHorario, Profesor hIdprofesor, String dia, Date horaInicio, Date horaFin, Boolean disponible) {
        this.idHorario = idHorario;
        this.hIdprofesor = hIdprofesor;
        this.dia = dia;
        this.horaInicio = horaInicio;
        this.horaFin = horaFin;
        this.disponible = disponible;
    }
    public Horario(int idHorario, Profesor hIdprofesor, String dia, Date horaInicio, Date horaFin, Boolean disponible, List<Asesorar> asesorar) {
       this.idHorario = idHorario;
       this.hIdprofesor = hIdprofesor;
       this.dia = dia;
       this.horaInicio = horaInicio;
       this.horaFin = horaFin;
       this.disponible = disponible;
       this.asesorar = asesorar;
    }
   
    public int getIdHorario() {
        return this.idHorario;
    }
    
    public void setIdHorario(int idHorario) {
        this.idHorario = idHorario;
    }
    public Profesor getProfesor() {
        return this.hIdprofesor;
    }
    
    public void setProfesor(Profesor hIdprofesor) {
        this.hIdprofesor = hIdprofesor;
    }
    public String getDia() {
        return this.dia;
    }
    
    public void setDia(String dia) {
        this.dia = dia;
    }
    public Date getHoraInicio() {
        return this.horaInicio;
    }
    
    public void setHoraInicio(Date horaInicio) {
        this.horaInicio = horaInicio;
    }
    public Date getHoraFin() {
        return this.horaFin;
    }
    
    public void setHoraFin(Date horaFin) {
        this.horaFin = horaFin;
    }
    public Boolean getDisponible() {
        return this.disponible;
    }
    
    public void setDisponible(Boolean disponible) {
        this.disponible = disponible;
    }
    public List<Asesorar> getAsesorar() {
        return this.asesorar;
    }
    
    public void setAsesorar(List<Asesorar> asesorar) {
        this.asesorar = asesorar;
    }




}


