package modelo;
// Generated 2/10/2018 03:11:32 PM by Hibernate Tools 4.3.1
import java.io.Serializable;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Column;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.ManyToOne;

/**
 * Interesar generated by hbm2java
 */
@Entity
@Table(name = "Interesar")
public class Interesar  implements Serializable {

    @Id
    @Column(name = "idInteresar")
     private int idInteresar;
    @Column(name = "iIdmateria")
    @ManyToOne(fetch = FetchType.LAZY)
     private Materia iIdmateria;
    @Column(name = "iIdNivel")
    @ManyToOne(fetch = FetchType.LAZY)
     private Nivel iIdNivel;
    @Column(name = "iIdTema")
    @ManyToOne(fetch = FetchType.LAZY)
     private Tema iIdTema;
    @Column(name = "iIdUsuario")
    @ManyToOne(fetch = FetchType.LAZY)
     private Usuario iIdUsuario;

    public Interesar() {
    }

    public Interesar(int idInteresar, Materia iIdmateria, Nivel iIdNivel, Tema iIdTema, Usuario iIdUsuario) {
       this.idInteresar = idInteresar;
       this.iIdmateria = iIdmateria;
       this.iIdNivel = iIdNivel;
       this.iIdTema = iIdTema;
       this.iIdUsuario = iIdUsuario;
    }
   
    public int getIdinteresar() {
        return this.idInteresar;
    }
    
    public void setIdinteresar(int idInteresar) {
        this.idInteresar = idInteresar;
    }
    public Materia getMateria() {
        return this.iIdmateria;
    }
    
    public void setMateria(Materia iIdmateria) {
        this.iIdmateria = iIdmateria;
    }
    public Nivel getNivel() {
        return this.iIdNivel;
    }
    
    public void setNivel(Nivel iIdNivel) {
        this.iIdNivel = iIdNivel;
    }
    public Tema getTema() {
        return this.iIdTema;
    }
    
    public void setTema(Tema iIdTema) {
        this.iIdTema = iIdTema;
    }
    public Usuario getUsuario() {
        return this.iIdUsuario;
    }
    
    public void setUsuario(Usuario iIdUsuario) {
        this.iIdUsuario = iIdUsuario;
    }




}


