package modelo;
// Generated 2/10/2018 03:11:32 PM by Hibernate Tools 4.3.1
import java.util.HashSet;
import java.util.Set;
import java.io.Serializable;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Column;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.ManyToOne;
/**
 * Resena generated by hbm2java
 */
@Entity
@Table(name = "Resena")
public class Resena  implements Serializable {

    @Id
    @Column(name = "idResena")
     private Integer idResena;
    @Column(name = "rIdUsuraio")     
    @ManyToOne(fetch = FetchType.LAZY)
     private Usuario rIdUsuraio;
    @Column(name = "comentario")     
     private String comentario;
    @Column(name = "calificacion")     
     private int calificacion;

    public Resena() {
    }

	
    public Resena(Usuario rIdUsuraio, int calificacion) {
        this.rIdUsuraio = rIdUsuraio;
        this.calificacion = calificacion;
    }
    public Resena(Usuario rIdUsuraio, String comentario, int calificacion) {
       this.rIdUsuraio = rIdUsuraio;
       this.comentario = comentario;
       this.calificacion = calificacion;
    }
   
    public Integer getIdResena() {
        return this.idResena;
    }
    
    public void setIdResena(Integer idResena) {
        this.idResena = idResena;
    }
    public Usuario getUsuraio() {
        return this.rIdUsuraio;
    }
    
    public void setUsuraio(Usuario rIdUsuraio) {
        this.rIdUsuraio = rIdUsuraio;
    }
    public String getComentario() {
        return this.comentario;
    }
    
    public void setComentario(String comentario) {
        this.comentario = comentario;
    }
    public int getCalificacion() {
        return this.calificacion;
    }
    
    public void setCalificacion(int calificacion) {
        this.calificacion = calificacion;
    }




}


