package modelo;
// Generated 2/10/2018 03:11:32 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.io.Serializable;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Column;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.ManyToOne;

/**
 * Tarjeta generated by hbm2java
 */
@Entity
@Table(name = "Tarjeta")
public class Tarjeta  implements Serializable {

    @Id
    @Column(name = "idTarjeta")
     private int idTarjeta;
    @Column(name = "tIdUsuario")     
    @ManyToOne(fetch = FetchType.LAZY)
     private Usuario tIdUsuario;
    @Column(name = "ccv")     
     private int ccv;
    @Column(name = "numero")     
     private int numero;
    @Column(name = "vencimiento")     
     private Date vencimiento;

    public Tarjeta() {
    }

    public Tarjeta(int idTarjeta, Usuario tIdUsuario, int ccv, int numero, Date vencimiento) {
       this.idTarjeta = idTarjeta;
       this.tIdUsuario = tIdUsuario;
       this.ccv = ccv;
       this.numero = numero;
       this.vencimiento = vencimiento;
    }
   
    public int getIdTarjeta() {
        return this.idTarjeta;
    }
    
    public void setIdTarjeta(int idTarjeta) {
        this.idTarjeta = idTarjeta;
    }
    public Usuario getUsuario() {
        return this.tIdUsuario;
    }
    
    public void setUsuario(Usuario tIdUsuario) {
        this.tIdUsuario = tIdUsuario;
    }
    public int getCcv() {
        return this.ccv;
    }
    
    public void setCcv(int ccv) {
        this.ccv = ccv;
    }
    public int getNumero() {
        return this.numero;
    }
    
    public void setNumero(int numero) {
        this.numero = numero;
    }
    public Date getVencimiento() {
        return this.vencimiento;
    }
    
    public void setVencimiento(Date vencimiento) {
        this.vencimiento = vencimiento;
    }




}


